name: RunTest

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}
      - name: Install
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - name: Run test-coverage
        run: make test-coverage

      - name: Run Codeclimate test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0

        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true